const projects = [
  {
    id: 1,
    name: "Todo list App",
    shortName: "TodoApp",
    desc: "Frontendmentor's Todo App Challenge",
    thumb: require("./img/todo1.png"),
    img: require("./img/todo1.png"),
    img2: require("./img/todo2.png"),
    demo: "https://simple-todo-web.vercel.app",
    tech: ["html","css","javascript","vercel"],
  },
  {
    id: 2,
    name: "Joki-ku's landing page",
    shortName: "Joki-ku",
    desc: "Just a placeholder text and placeholder project. Real project soon will be added. restriction of air and airway, military personnel, initial encounter",
    thumb: require("./img/jok1.png"),
    img: require("./img/jok1.png"),
    img2: require("./img/jok2.png"),
    demo: "https://kadabengarann.github.io/joki-ku",
    tech: ["html","css","javascript","github"],
},
  {
    id: 3,
    name: "Sistem Informasi Akreditasi Fakultas Teknik ULM",
    shortName: "SI-Akre FT ULM",
    desc: "Just a placeholder text and placeholder project. Real project soon will be added",
    thumb: require("./img/akre1.png"),
    img: require("./img/akre1.png"),
    img2: require("./img/akre2.png"),
    demo: "#", 
    tech: ["html","css","javascript","php","laravel"],
  },
  {
    id: 4,
    name: "Quizpancasila",
    shortName: "Quizpancasila",
    desc: "Just a dummy text, no biggie. Sprain of joints and ligaments of unspecified parts of neck  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequuntur architecto cumque accusantium rerum mollitia in. Aliquid nam ad earum quod porro iure facilis ducimus minima cupiditate omnis rem, molestias unde nisi! Dolores vero delectus voluptatem atque.",
    thumb: require("./img/panc1.png"),
    img: require("./img/panc1.png"),
    img2: require("./img/panc2.png"),
    demo: "https://quizpancasila-proto.web.app",
    tech: ["html","css","jquery","fire-store","fire-auth","pwa"],

  },
  {
    id: 5,
    name: "Bookshelf App",
    shortName: "Bookshelf App",
    desc: "Just a dummy text, no biggie. Sprain of joints and ligaments of unspecified parts of neck  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequuntur architecto cumque accusantium rerum mollitia in. Aliquid nam ad earum quod porro iure facilis ducimus minima cupiditate omnis rem, molestias unde nisi! Dolores vero delectus voluptatem atque. Veniam nisi voluptas at blanditiis suscipit libero quis saepe amet iusto quo, voluptatem dolores obcaecati tempora. Eaque totam at iure sit atque, minima odit voluptatum vel in et eum explicabo ea dicta quod?",
    thumb: require("./img/book1.png"),
    img: require("./img/book1.png"),
    img2: require("./img/book2.png"),
    demo: "https://kadabengarann.github.io/bookshelf-app/",
    tech: ["html","css","javascript","github"],
  },
  {
    id: 6,
    name: "Rock Paper Scissors Game",
    shortName: "Rock-Paper-Scissors",
    desc: "Frontendmentor's Rock Paper Scissors Challenge, subsequent encounter",
    thumb: require("./img/osom1.png"),
    img: require("./img/osom1.png"),
    img2: require("./img/osom2.png"),
    demo: "https://kadabengarann.github.io/osom",  
    tech: ["html","css","javascript","github"],
  },
];
export default projects;
