const projects = [
  {
    id: "narasource",
    name: "Narasource",
    shortName: "Narasource",
    role:"Mobile Developer",
    place:"PT Media Kreasi Abadi",
    type:"internship",
		category: "Android",
    desc: "Narasource is an Android application developed to simplify the process of finding reliable interviewees for various topics. It aims to provide a seamless experience in resolving problems, especially in obtaining valid and trustworthy information. The app also features integrated virtual meetings, enabling smooth and efficient communication between users and interviewees.<br><br> Key Features of Narasource include:<br><ol><li>Registering as a Narasumber (Interviewee)</li><li>Searching for Narasumber (Interviewees)</li><li>Access to informative articles</li><li>Virtual meeting</li></ol><br>Narasource significantly assists users in efficiently locating trustworthy interviewees, saving valuable time during the search process. With this application, you can easily find reliable and credible interviewees tailored to your specific needs.<br><br>Narasource is the ultimate solution for your Narasumber search requirements. Experience the convenience and efficiency it offers in finding the right interviewees for your topics.",
    thumb: require("./img/narasource1.png"),
    img: require("./img/narasource1.png"),
    img2: require("./img/narasource2.png"),
    demo: "https://github.com/kadabengarann/narasource/releases/tag/v1.0.0-alpha",
    repo: "https://github.com/kadabengarann/narasource",
    tech: ["kotlin","zoom-sdk"],
  },
  {
    id: "wastecreative",
    name: "WasteCreative",
    shortName: "WasteCreative",
    role:"Mobile Developer",
    place:"Google Bangkit Capstone Project",
    type:"capstone",
		category: "Android",
    desc: "WasteCreative is an android application designed to help people with household waste management.<br><br>Our application helps manage household waste by detecting household waste objects with the implementation of Machine Learning and providing craft recommendations that can be made based on the detection results.<br><br>Besides being able to reduce the amount of household waste, our application also has the potential to help improve the welfare of MSMEs in the creative industry by providing a fourm marketplace platform for buying and selling handicrafts that have been made.",
    thumb: require("./img/wastecreative1.png"),
    img: require("./img/wastecreative1.png"),
    img2: require("./img/wastecreative2.png"),
    demo: "https://github.com/kadabengarann/waste-creative",
    repo: "https://github.com/kadabengarann/waste-creative",
    tech: ["kotlin","tflite","fire-auth"],
  },
  {
    id: "quizpancasila",
    name: "Quizpancasila",
    shortName: "Quizpancasila",
    role:"Front-End Web Developer",
    type:"personal",
		category: "Website",
    desc: "Quizpancasila is a Quiz WebApp to test knowledge about Indonesian Civic Education (PKn) and Pancasila.",
    thumb: require("./img/panc1.png"),
    img: require("./img/panc1.png"),
    img2: require("./img/panc2.png"),
    demo: "https://quizpancasila-proto.web.app",
    repo: "https://github.com/kadabengarann/quizpancasila",
    tech: ["html","css","jquery","fire-store","fire-auth","pwa"],
  },
  {
    id: "story-app",
    name: "StoryApp",
    shortName: "StoryApp",
    role:"Mobile Developer",
    type: "personal",
		category: "Android",
    desc: "StoryApp is an Android application designed to help you share your stories with the world. This project was developed as a submission for the Intermediate Android class on Dicoding Academy, incorporating several key functionalities. It implements a Single Source of Truth using Room, ensuring data consistency and reliability, along with offline functionality. The app also includes user authentication using email and password, data consumption from APIs, and the integration of Google Maps for displaying user locations<br><br> Key Features:<br><ol><li>Upload Your Story</li><li>Location Sharing</li><li>Find Other Users' Locations</li><li>Login & Register</li><li>Explore Other Stories</li></ol>",
    thumb: require("./img/story1.png"),
    img: require("./img/story1.png"),
    img2: require("./img/story2.png"),
    demo: "https://github.com/kadabengarann/story-app/releases/tag/v1.0",
    repo: "https://github.com/kadabengarann/story-app",
    tech: ["kotlin"]
  },
  {
    id: "useful-app-review-classification",
    name: "Useful App Review Classification",
    shortName: "Useful App Review Classification",
    role: "Researcher",
		place:"Undergraduate thesis research @Information Technology - Lambung Mangkurat University",
    type: "thesis",
		category: "Machine Learning",
    desc: "\”Useful App Review Classification\" is a machine learning project that utilizes the IndoBERT-BiLSTM model, to automate the classification of app reviews as "Useful" or "Not Useful." The project provides a user-friendly web interface powered by Streamlit and Hugging Face Space, enabling users to classify individual reviews or upload multiple reviews in CSV format for efficient evaluation. This solution aims to simplify the process of assessing app reviews, aiding developers in effectively assessing the quality and functionality of their applications. Experiment results demonstrate that the IndoBERT-BiLSTM model achieves the best performance with an accuracy rate of 95.49%, representing a 1.16% improvement over the fine-tuned IndoBERT model.",
    thumb: require("./img/panc1.png"), /*ss app*/
    img: require("./img/panc1.png"),  /*ss app*/
    img2: require("./img/panc2.png"),  /*ss Model struktur*/
    demo: "https://huggingface.co/spaces/kadabengaran/useful-review-classification",
    repo: "https://github.com/kadabengarann/useful-review-classification-webapp",
    tech: []
  },
  {
    id: "si-akre",
    name: "Sistem Informasi Akreditasi Fakultas Teknik ULM",
    shortName: "SI-Akre FT ULM",
    role:"Web Developer",
    place:"Information Technology Department of Lambung Mangkurat University",
    type:"internship",
		category: "Website",
    desc: "SI-Akre is a Web Application for data entry and archiving on the Accreditation of Information Technology study program, Faculty of Engineering, University of Lambung Mangkurat.<br><br>This Website is suitable for assisting in the process of archiving and managing accreditation documents, as well as for improving the quality of the archiving process and document management for accreditation purposes in the Information Technology Study Program.",
    thumb: require("./img/akre1.png"),
    img: require("./img/akre1.png"),
    img2: require("./img/akre2.png"),
    demo: "#", 
    tech: ["html","css","javascript","php","laravel"],
  },
  {
    id: "bookshelf-app",
    name: "Bookshelf App",
    shortName: "Bookshelf App",
    role:"FullStack Web Developer",
    type:"personal",
		category: "Website",
    desc: "Bookshelf App is a web application designed to help manage user's book reading data. This website is utilizing DOM, Event, and Web Storage manipulation techniques.",
    thumb: require("./img/book1.png"),
    img: require("./img/book1.png"),
    img2: require("./img/book2.png"),
    demo: "https://kadabengarann.github.io/bookshelf-app/",
    tech: ["html","css","javascript","github"],
  },
  {
    id: "todo-app",
    name: "Todo list App",
    shortName: "TodoApp",
    role:"Front-End Web Developer",
    type:"personal",
		category: "Website",
    desc: "Todo list App is Frontendmentor's Challenge.<br><br>This app includes a dark/light theme toggle and drag & drop for reordering task list items.",
    thumb: require("./img/todo1.png"),
    img: require("./img/todo1.png"),
    img2: require("./img/todo2.png"),
    demo: "https://simple-todo-web.vercel.app",
    tech: ["html","css","javascript","vercel"],
  },
  {
    id: "joki-ku",
    name: "Joki-ku's landing page",
    shortName: "Joki-ku",
    role:"Front-End Web Developer",
    type:"personal",
		category: "Website",
    desc: "A simple landing page",
    thumb: require("./img/jok1.png"),
    img: require("./img/jok1.png"),
    img2: require("./img/jok2.png"),
    demo: "https://kadabengarann.github.io/joki-ku",
    tech: ["html","css","javascript","github"],
},
  {
    id: "osom-game",
    name: "Rock Paper Scissors Game",
    shortName: "Rock-Paper-Scissors",
    role:"Front-End Web Developer",
    type:"personal",
		category: "Website",
    desc: "Frontendmentor's Rock Paper Scissors Challenge",
    thumb: require("./img/osom1.png"),
    img: require("./img/osom1.png"),
    img2: require("./img/osom2.png"),
    demo: "https://kadabengarann.github.io/osom",  
    tech: ["html","css","javascript","github"],
  },
];
export default projects;
