const projects = [
  {
    id: 1,
    name: "Flexidy",
    desc: "Sprain of joints and ligaments of unspecified parts of neck  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequuntur architecto cumque accusantium rerum mollitia in. Aliquid nam ad earum quod porro iure facilis ducimus minima cupiditate omnis rem, molestias unde nisi! Dolores vero delectus voluptatem atque. Veniam nisi voluptas at blanditiis suscipit libero quis saepe amet iusto quo, voluptatem dolores obcaecati tempora. Eaque totam at iure sit atque, minima odit voluptatum vel in et eum explicabo ea dicta quod?",
    thumb: require("./img/bg-jumbo-1.jpg"),
    img: require("./img/bg-jumbo-1.jpg"),
    img2: require("./img/bg-jumbo-1.jpg"),
    demo: "http://virginia.edu/enim/in.png?pede=congue&venenatis=risus&non=semper&sodales=porta&sed=volutpat&tincidunt=quam&eu=pede&felis=lobortis&fusce=ligula&posuere=sit&felis=amet&sed=eleifend&lacus=pede&morbi=libero&sem=quis&mauris=orci&laoreet=nullam&ut=molestie&rhoncus=nibh&aliquet=in&pulvinar=lectus&sed=pellentesque&nisl=at&nunc=nulla&rhoncus=suspendisse&dui=potenti&vel=cras&sem=in&sed=purus&sagittis=eu&nam=magna&congue=vulputate&risus=luctus&semper=cum&porta=sociis&volutpat=natoque&quam=penatibus&pede=et&lobortis=magnis&ligula=dis&sit=parturient&amet=montes&eleifend=nascetur&pede=ridiculus&libero=mus&quis=vivamus&orci=vestibulum&nullam=sagittis&molestie=sapien&nibh=cum&in=sociis&lectus=natoque&pellentesque=penatibus&at=et&nulla=magnis&suspendisse=dis&potenti=parturient&cras=montes&in=nascetur&purus=ridiculus&eu=mus&magna=etiam&vulputate=vel&luctus=augue&cum=vestibulum&sociis=rutrum&natoque=rutrum&penatibus=neque",
  },
  {
    id: 2,
    name: "Latlux",
    desc: "War operations involving intentional restriction of air and airway, military personnel, initial encounter",
    thumb: require("./img/bg-jumbo-2.jpg"),
    img: require("./img/bg-jumbo-2.jpg"),
    img2: require("./img/bg-jumbo-2.jpg"),
    demo: "http://desdev.cn/id/sapien/in/sapien/iaculis/congue.png?nisl=amet&nunc=eleifend&rhoncus=pede&dui=libero&vel=quis&sem=orci&sed=nullam&sagittis=molestie&nam=nibh&congue=in&risus=lectus&semper=pellentesque&porta=at&volutpat=nulla&quam=suspendisse&pede=potenti&lobortis=cras&ligula=in&sit=purus&amet=eu&eleifend=magna&pede=vulputate&libero=luctus&quis=cum&orci=sociis&nullam=natoque&molestie=penatibus&nibh=et&in=magnis&lectus=dis&pellentesque=parturient&at=montes&nulla=nascetur&suspendisse=ridiculus&potenti=mus&cras=vivamus&in=vestibulum&purus=sagittis&eu=sapien&magna=cum&vulputate=sociis&luctus=natoque&cum=penatibus&sociis=et&natoque=magnis&penatibus=dis&et=parturient&magnis=montes&dis=nascetur&parturient=ridiculus&montes=mus&nascetur=etiam&ridiculus=vel&mus=augue&vivamus=vestibulum&vestibulum=rutrum&sagittis=rutrum&sapien=neque&cum=aenean&sociis=auctor&natoque=gravida&penatibus=sem&et=praesent&magnis=id&dis=massa&parturient=id&montes=nisl&nascetur=venenatis&ridiculus=lacinia&mus=aenean&etiam=sit&vel=amet&augue=justo&vestibulum=morbi&rutrum=ut&rutrum=odio&neque=cras&aenean=mi&auctor=pede&gravida=malesuada&sem=in&praesent=imperdiet&id=et&massa=commodo&id=vulputate&nisl=justo&venenatis=in&lacinia=blandit&aenean=ultrices&sit=enim&amet=lorem&justo=ipsum&morbi=dolor",
  },
  {
    id: 3,
    name: "Tresom",
    desc: "Nondisplaced fracture of shaft of other metacarpal bone",
    thumb: require("./img/bg-jumbo-3.jpg"),
    img: require("./img/bg-jumbo-3.jpg"),
    img2: require("./img/bg-jumbo-3.jpg"),
    demo: "https://ask.com/massa/quis/augue/luctus.js?potenti=ut&nullam=volutpat&porttitor=sapien&lacus=arcu&at=sed&turpis=augue&donec=aliquam&posuere=erat&metus=volutpat&vitae=in&ipsum=congue&aliquam=etiam&non=justo&mauris=etiam&morbi=pretium&non=iaculis&lectus=justo&aliquam=in&sit=hac&amet=habitasse&diam=platea&in=dictumst&magna=etiam&bibendum=faucibus&imperdiet=cursus&nullam=urna&orci=ut&pede=tellus&venenatis=nulla&non=ut&sodales=erat&sed=id",
  },
  {
    id: 4,
    name: "Voyatouch",
    desc: "Charcot's joint",
    thumb: require("./img/bg-jumbo-1.jpg"),
    img: require("./img/bg-jumbo-1.jpg"),
    img2: require("./img/bg-jumbo-1.jpg"),
    demo: "http://cnbc.com/vitae/quam/suspendisse.html?enim=justo&in=morbi&tempor=ut&turpis=odio&nec=cras&euismod=mi&scelerisque=pede&quam=malesuada&turpis=in&adipiscing=imperdiet&lorem=et&vitae=commodo&mattis=vulputate&nibh=justo&ligula=in&nec=blandit&sem=ultrices&duis=enim&aliquam=lorem&convallis=ipsum&nunc=dolor&proin=sit&at=amet&turpis=consectetuer&a=adipiscing&pede=elit&posuere=proin&nonummy=interdum&integer=mauris&non=non&velit=ligula&donec=pellentesque&diam=ultrices&neque=phasellus&vestibulum=id&eget=sapien&vulputate=in&ut=sapien&ultrices=iaculis&vel=congue&augue=vivamus&vestibulum=metus&ante=arcu&ipsum=adipiscing&primis=molestie&in=hendrerit&faucibus=at&orci=vulputate&luctus=vitae&et=nisl&ultrices=aenean&posuere=lectus&cubilia=pellentesque&curae=eget&donec=nunc&pharetra=donec&magna=quis&vestibulum=orci&aliquet=eget&ultrices=orci&erat=vehicula&tortor=condimentum&sollicitudin=curabitur&mi=in&sit=libero&amet=ut&lobortis=massa&sapien=volutpat&sapien=convallis&non=morbi&mi=odio&integer=odio&ac=elementum&neque=eu&duis=interdum&bibendum=eu&morbi=tincidunt&non=in&quam=leo&nec=maecenas&dui=pulvinar&luctus=lobortis&rutrum=est&nulla=phasellus&tellus=sit&in=amet&sagittis=erat&dui=nulla&vel=tempus&nisl=vivamus",
  },
  {
    id: 5,
    name: "Bigtax",
    desc: "Exposure to other electric current",
    thumb: require("./img/bg-jumbo-2.jpg"),
    img: require("./img/bg-jumbo-2.jpg"),
    img2: require("./img/bg-jumbo-2.jpg"),
    demo: "http://paypal.com/integer/pede/justo/lacinia/eget/tincidunt/eget.xml?nisi=quis&nam=libero&ultrices=nullam&libero=sit&non=amet",
  },
  {
    id: 6,
    name: "Voyatouch",
    desc: "Contusion of prostate, subsequent encounter",
    thumb: require("./img/bg-jumbo-3.jpg"),
    img: require("./img/bg-jumbo-3.jpg"),
    img2: require("./img/bg-jumbo-3.jpg"),
    demo: "https://xinhuanet.com/duis/consequat/dui.js?in=mauris&congue=vulputate&etiam=elementum&justo=nullam&etiam=varius&pretium=nulla&iaculis=facilisi&justo=cras&in=non&hac=velit&habitasse=nec&platea=nisi&dictumst=vulputate&etiam=nonummy&faucibus=maecenas&cursus=tincidunt&urna=lacus&ut=at&tellus=velit&nulla=vivamus&ut=vel&erat=nulla&id=eget&mauris=eros&vulputate=elementum&elementum=pellentesque&nullam=quisque&varius=porta&nulla=volutpat&facilisi=erat&cras=quisque&non=erat&velit=eros&nec=viverra&nisi=eget&vulputate=congue&nonummy=eget&maecenas=semper&tincidunt=rutrum&lacus=nulla&at=nunc&velit=purus&vivamus=phasellus&vel=in&nulla=felis&eget=donec&eros=semper&elementum=sapien&pellentesque=a&quisque=libero&porta=nam&volutpat=dui&erat=proin&quisque=leo&erat=odio&eros=porttitor&viverra=id&eget=consequat&congue=in&eget=consequat&semper=ut&rutrum=nulla&nulla=sed&nunc=accumsan",
  },
  {
    id: 7,
    name: "Zathin",
    desc: "Struck by other fish, subsequent encounter",
    thumb: require("./img/bg-jumbo-1.jpg"),
    img: require("./img/bg-jumbo-1.jpg"),
    img2: require("./img/bg-jumbo-1.jpg"),
    demo: "https://naver.com/lectus/pellentesque.html?etiam=non&pretium=velit&iaculis=nec&justo=nisi&in=vulputate&hac=nonummy&habitasse=maecenas&platea=tincidunt&dictumst=lacus&etiam=at&faucibus=velit&cursus=vivamus&urna=vel&ut=nulla&tellus=eget&nulla=eros&ut=elementum&erat=pellentesque&id=quisque&mauris=porta&vulputate=volutpat&elementum=erat&nullam=quisque&varius=erat&nulla=eros&facilisi=viverra&cras=eget&non=congue&velit=eget&nec=semper&nisi=rutrum&vulputate=nulla&nonummy=nunc&maecenas=purus&tincidunt=phasellus&lacus=in&at=felis&velit=donec&vivamus=semper&vel=sapien&nulla=a&eget=libero&eros=nam&elementum=dui&pellentesque=proin&quisque=leo&porta=odio",
  },
  {
    id: 8,
    name: "Tin",
    desc: "Displacement of implanted electronic neurostimulator of spinal cord electrode (lead)",
    thumb: require("./img/bg-jumbo-2.jpg"),
    img: require("./img/bg-jumbo-2.jpg"),
    img2: require("./img/bg-jumbo-2.jpg"),
    demo: "http://epa.gov/in/purus/eu/magna.js?tempus=non&semper=velit&est=nec&quam=nisi&pharetra=vulputate&magna=nonummy&ac=maecenas&consequat=tincidunt&metus=lacus&sapien=at&ut=velit&nunc=vivamus&vestibulum=vel&ante=nulla&ipsum=eget&primis=eros&in=elementum&faucibus=pellentesque&orci=quisque&luctus=porta&et=volutpat",
  },
  {
    id: 9,
    name: "Kanlam",
    desc: "Animal-rider injured in collision with fixed or stationary object, initial encounter",
    thumb: require("./img/bg-jumbo-3.jpg"),
    img: require("./img/bg-jumbo-3.jpg"),
    img2: require("./img/bg-jumbo-3.jpg"),
    demo: "https://mashable.com/convallis/morbi.xml?vel=suscipit&augue=ligula&vestibulum=in&ante=lacus&ipsum=curabitur&primis=at&in=ipsum&faucibus=ac&orci=tellus&luctus=semper&et=interdum&ultrices=mauris&posuere=ullamcorper&cubilia=purus&curae=sit&donec=amet&pharetra=nulla&magna=quisque",
  },
  {
    id: 10,
    name: "Trippledex",
    desc: "Neonatal bradycardia",
    thumb: require("./img/bg-jumbo-1.jpg"),
    img: require("./img/bg-jumbo-1.jpg"),
    img2: require("./img/bg-jumbo-1.jpg"),
    demo: "https://yahoo.com/justo/sollicitudin/ut/suscipit/a/feugiat/et.jsp?justo=potenti&nec=cras&condimentum=in&neque=purus&sapien=eu&placerat=magna&ante=vulputate&nulla=luctus&justo=cum&aliquam=sociis&quis=natoque&turpis=penatibus&eget=et&elit=magnis&sodales=dis&scelerisque=parturient&mauris=montes&sit=nascetur&amet=ridiculus&eros=mus&suspendisse=vivamus&accumsan=vestibulum&tortor=sagittis&quis=sapien&turpis=cum&sed=sociis&ante=natoque&vivamus=penatibus&tortor=et&duis=magnis&mattis=dis&egestas=parturient&metus=montes&aenean=nascetur&fermentum=ridiculus&donec=mus&ut=etiam&mauris=vel&eget=augue&massa=vestibulum&tempor=rutrum&convallis=rutrum&nulla=neque&neque=aenean&libero=auctor&convallis=gravida&eget=sem&eleifend=praesent&luctus=id&ultricies=massa&eu=id&nibh=nisl&quisque=venenatis&id=lacinia&justo=aenean&sit=sit&amet=amet&sapien=justo&dignissim=morbi&vestibulum=ut&vestibulum=odio&ante=cras&ipsum=mi&primis=pede",
  },
];
export default projects;
